version: '3'
services:
  ##mysql配置
  mysql:
    environment:
      ##root账号的密码
      MYSQL_ROOT_PASSWORD: "qwer1234"
    image: "docker.io/mysql:8.0.29"
    container_name: mysql
    restart: always
    ##映射挂载
    volumes:
      ##数据目录，要确保先创建好
      - "$PWD/mysql/data:/var/lib/mysql"
      - "$PWD/mysql/conf:/etc/mysql/conf.d/"
    ports:
      - "3306:3306"
  ##redis配置
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes --requirepass "123456"
    ports:
      - "6379:6379"
    volumes:
      ##数据目录，要确保先创建好
      - "$PWD/redis/data:/data"
  java:
    image: openjdk:11
    container_name: yeb-server
    ports:
      - "8080:8080"
    volumes:
      - "$PWD/java/yeb-server.jar:/data/yeb-server.jar"
    ##这是java项目的环境变量，yml文件配置
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
      - SPRING_REDIS_PASSWORD=123456
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=qwer1234
    entrypoint: java -jar /data/yeb-server.jar
    depends_on:
      - redis
      - mysql
